version: '3'

services:
  dump1090:
    image: jraviles/dump1090
    ports:
      - 8080:8080/tcp
    devices:
      - /dev/bus/usb
    restart: unless-stopped

  piaware:
    build:
     context: 'https://github.com/wnagele/docker-piaware.git'
    env_file: 'flightaware_credentials.txt'
    environment:
      - BEAST_PORT_30005_TCP_ADDR=dump1090
    restart: unless-stopped

  adsb-exchange:
    build:
      context: 'https://github.com/webmonkey/docker-adsbexchange.git'
    links:
      - dump1090:decoder
    restart: unless-stopped

  adsbhub:
    image: jraviles/adsbhub
    restart: unless-stopped
